{
 "title": "My API services",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Security requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_total[1m])*100",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Requests to S3 storage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(minio_s3_requests_total[1m])*100",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Uploader requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total[1m])*100",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}