apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-app-chart.fullname" . }}-back
  labels:
    {{- include "helm-app-chart.labels" . | nindent 4 }}
    {{- toYaml .Values.labels.back | nindent 4 }}
spec:
  type: {{ .Values.service.back.type }}
  ports:
    - port: {{ .Values.service.back.port }}
      targetPort: {{ .Values.endpoint.back }}
      protocol: TCP
  selector:
    {{- include "helm-app-chart.selectorLabels" . | nindent 4 }}
    {{- toYaml .Values.labels.back | nindent 4 }}
