apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-app-chart.fullname" . }}-front
  labels:
    {{- include "helm-app-chart.labels" . | nindent 4 }}
    {{- toYaml .Values.labels.front | nindent 4 }}
spec:
  type: {{ .Values.service.front.type }}
  ports:
    - port: {{ .Values.service.front.port }}
      targetPort: {{ .Values.endpoint.front }}
      protocol: TCP
  selector:
    {{- include "helm-app-chart.selectorLabels" . | nindent 4 }}
    {{- toYaml .Values.labels.front | nindent 4 }}
