apiVersion: v1
kind: ConfigMap
metadata:
  name: task1-config
  namespace: stage
data:
  backend.env: |-
    DATABASE_URL=postgres://postgres:postgres@task1-db.stage:5432/news
  frontend.env: |-
    BASE_URL=http://localhost:9000
