# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
  'netology-kubenode-01',
  'netology-kubenode-02',
  'netology-kubenode-03',
]

Vagrant.configure("2") do |config|

	boxes.each do |box|
		config.vm.define box do |node|
			node.vm.box = "bento/ubuntu-20.04"
			node.vm.synced_folder ".", "/vagrant", disabled: true
			node.vm.hostname = 	box
			node.vm.provider "hyperv" do |h|
				h.cpus = 2
				h.memory = 2048
				h.linked_clone = true
				h.vmname = box
				h.vm_integration_services = {
					guest_service_interface: true,
					heartbeat: true,
					shutdown: true,
					time_synchronization: true
				}
			end
		end
	end
end
