apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-dynamic-volume-claim
  namespace: production
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---     
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2-deployment-back
  namespace: production
  labels:
    app: task2-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task2-back
  template:
    metadata:
      labels:
        app: task2-back
    spec:
      nodeName: node1
      containers:
      - name: netology-backend
        image: nimlock/netology-homework-13.xx-backend:production
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: backend-env
          mountPath: /app/.env
          subPath: .env
          readOnly: true
        - name: nfs-volume
          mountPath: /nfs-in-back
      volumes:
      - name: backend-env
        configMap:
          name: task2-config
          items:
            - key: backend.env
              path: .env
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: test-dynamic-volume-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2-deployment-front
  namespace: production
  labels:
    app: task2-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task2-front
  template:
    metadata:
      labels:
        app: task2-front
    spec:
      nodeName: node2
      containers:
      - name: netology-frontend
        image: nimlock/netology-homework-13.xx-frontend:production
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-env
          mountPath: /app/.env
          subPath: .env
          readOnly: true
        - name: nfs-volume
          mountPath: /nfs-in-front
      volumes:
      - name: frontend-env
        configMap:
          name: task2-config
          items:
            - key: frontend.env
              path: .env
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: test-dynamic-volume-claim
